INSERT INTO XFLOW_PROCESS_INSTANCE_PATH
(RECORD_ID,TO_PATH_ID,TO_PATH_NAME,TO_ACTIVITY_TYPE,TO_ACTIVITY_NAME,TO_ACTIVITY_ID) 
VALUES (:recordId, :toPathId, :toPathName, :toActivityType, :toActivityName, :toActivityId) 