INSERT INTO XFLOW_PROCESS_INSTANCE_RECORD 
(RECORD_ID,PROCESS_INSTANCE_ID,ACTIVITY_TYPE,ACTIVITY_NAME,
ACTIVITY_ID,CREATE_DATE,FROM_PATH,SN) 
VALUES ( :RECORD_ID,:PROCESS_INSTANCE_ID,:ACTIVITY_TYPE,:ACTIVITY_NAME,
:ACTIVITY_ID,:CREATE_DATE,:FROM_PATH,:SN )